---
- name: UPDATE KLAP
  hosts: all
  become: yes
  
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
      cache_valid_time: 3600
  
  - name: Update all installed packages
    apt:
      name: "*"
      state: latest
